# Generated by Django 4.2.7 on 2024-02-19 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="has_exchange",
        ),
        migrations.RemoveField(
            model_name="category",
            name="has_free",
        ),
        migrations.RemoveField(
            model_name="category",
            name="has_price",
        ),
    ]
