# Generated by Django 4.2.7 on 2024-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_category_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="title",
        ),
    ]
