# Generated by Django 4.2.7 on 2024-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_subcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
