# Generated by Django 4.2.7 on 2024-02-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_alter_category_title_alter_subcategory_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.CharField(max_length=128)),
                ("contact_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("subcategory", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="post.subcategory")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
