# Generated by Django 4.2.7 on 2024-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
