# Generated by Django 4.2.7 on 2024-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="phone_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
