# Generated by Django 4.2.7 on 2024-02-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Select", "Select"),
                            ("Choice", "Choice"),
                            ("Select Button", "Button"),
                            ("Text", "Text"),
                            ("Number", "Number"),
                            ("Multiple choice", "Multiple Choice"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=256, null=True)),
                ("is_required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=256)),
                ("order", models.IntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="values", to="option.option"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="option.option"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostOptionValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "option_value",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="option.optionvalue"),
                ),
                (
                    "post_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="values", to="option.postoption"
                    ),
                ),
            ],
            options={
                "unique_together": {("post_option", "option_value")},
            },
        ),
    ]
