# Generated by Django 4.2.7 on 2024-02-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
        ("option", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postoption",
            name="post",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="options", to="post.post"
            ),
            preserve_default=False,
        ),
    ]
