# Generated by Django 4.2.7 on 2024-02-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
        ("option", "0002_postoption_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("choice_text", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetailGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("is_multiple", models.BooleanField(default=False)),
                ("text", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetailPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="post.category")),
                (
                    "plan_detail",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="option.plandetail"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plandetail",
            name="group_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="option.plandetailgroup"
            ),
        ),
        migrations.CreateModel(
            name="Plan_Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField(default=0)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="post.category")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="option.plan")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_detail",
            field=models.ManyToManyField(related_name="plans", to="option.plandetail"),
        ),
    ]
